---
title: "Statistical Analysis and Modeling in Ecology"
subtitle: "Lecture 1 - Introduction"
author: "Thiago S. F. Silva (thiago.sf.silva@stir.ac.uk)"
date: "2019/04/07 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: xaringan-themer.css
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

---
class: inverse, center, middle

# About the course


---

```{r xaringan-themer, include = FALSE, echo = FALSE}
library(xaringanthemer)
duo_accent(
     primary_color = "#0c74d6",
     secondary_color = "#d86213",
    header_font_google = google_font("Alte Haas Grotesk"),
      text_font_google   = google_font("Roboto Condensed", "400", "400i"),
      code_font_google   = google_font("Fira Code")
)
```

Course Outline
==============

This course is composed of:

- ~~Blah, blah, blah, blah~~ ** Theoretical classes **

- ~~Fighting with R~~ ** Practical exercises **

- ~~Zzzzzzzzzzzzzzz~~ ** Paper discussions **

Assessments:

- ** Exercises: ** your scripts from practical classes

- ** Mini-project: ** group statistical analysis project

    - Use your own data or any available data
---

What we will cover
=======================

- Crash course into probabilities

- Probability distributions

- Frequentist error analysis ($ x + y $ Hypothesis testing :woman_facepalming:)

- Data organization and management

- Data visualization 

- General Linear Models (regression, ANOVA, ANCOVA)

- The very basics of machine learning for data analysis and prediction
---

What we will NOT cover
======================


- GLMs and GLMMs

- SEMS, path analysis, any other "fancy method"

- Multivariate analysis (Tadeu Siqueira)

### Why?

This course is focused on making you *THINK* statistically

Once you do, you can teach yourself any method

We try to avoid [statistical machismo](https://dynamicecology.wordpress.com/2012/09/11/statistical-machismo/)


---

About Me me Me
=============

**Thiago Sanna Freire Silva:** thiago.sf.silva@stir.ac.uk

*1998 - 2002*:        Biology B.Sc. - UFRN (Brazil)

*2003 - 2004*:        Remote Sensing M.Sc. - INPE (Brazil)

*2004 - 2009*:        Geography Ph.D. - University of Victoria (Canada)

*2009 - 2013*:        ~~slave~~ Postdoc at UCSB (USA) and INPE (Brazil)

*2013 - 2019*:        Assistant professor, Dept. of Geography, UNESP Rio Claro (Brazil)

*2019 - present*:     Lecturer, Biol. and Env. Sciences, University of Stirling (UK)

**Research Interests:** global change biology, ecosystem function, community assembly, plant functional ecology, biogeochemistry, macroecology, biogeography, remote sensing, data analysis, modeling.

---
class: center, middle

# About you?

---
class: center, middle

What is Statistics?
====================

---


What is Statistics?
====================

What Statistic ** is not **:

- A perfectly objective science

- A unique and foolproof method

- An automatic decision-making system

- A solution to all scientific problems

- The salvation for poor research

> "To consult the statistician after an experiment is finished is often
only to ask him to conduct a post mortem examination. 
> I can maybe say what the experiment died of. "
> `r tufte::quote_footer('- * Sir * Ronald Fisher.')`

---

What is Statistics?
====================

Mathematics Vs. Statistics: is it the same thing?

What is Statistics for?

Purpose of Statistics: to estimate and quantify ** uncertainties **

Uncertainties = ** probabilities **

What is Statistics?

How can we quantify uncertainties about something?

-   Comments\...

- Repetitions \ ...

- Experiments \ ...
---

What is Statistics?

Why do we want to quantify uncertainties about something?

- Decision \ ...

- Explanation ...

-   Prediction\...

Examples

- A reservoir has a 60% chance of eliminating the habitat of a
    species. But there is a 75% chance that the royalties investment will
    ensure the preservation of 500 km2 of primary forest in the surrounding
    of the reservoir. Should I authorize or veto the construction of this
    reservoir?

- What is the relative contribution of the hydrological regime,
    nutrients, and turbidity of water in the growth of aquatic plants
    in the Amazon?

- With what degree of certainty can I say that diversity will increase
    in 1.5 times when nutrient availability increases by 0.7
    times?

---

Statistical Modeling
=====================

Models

What is a ** model **?

`` `{r, out.width = '50% ', fig.align =' center ', echo = F}
knitr :: include_graphics ('figs / bruno.jpg')
(I.e.

---
Models

$ Y = \ beta _0 + \ beta _1 X $

---

! [image] (C: /Users/thiago/OneDrive/UNESP/Pos_graduacao/Eco/2015/Estatistica_2015/Aulas/Aula_1_Intro_2015/figs/landsat8.jpg) {width = "\ textwidth"}
---
! [image] (C: /Users/thiago/OneDrive/UNESP/Pos_graduacao/Eco/2015/Estatistica_2015/Aulas/Aula_1_Intro_2015/figs/casa.jpg) {width = "\ textwidth"}

---
What is a template?

- A ** simplified representation of reality

- It seeks to describe some aspects of interest, ignoring others

[** "All models are wrong. Some are useful" - George E. P. Box **] {. Alert}

---

### A taxonomy of models

** Warning: These relationships are * not * obligatory! **

---

Why use R?

** R: ** Software for Statistical Analysis and Programming - ** Use
compulsory in the course **.

- Free, free, has become "standard" for data analysis

- Difficult at first, but time is recovered after

- Programming = freedom

- All course exercises must be done in R

- Assumes that everyone has installed R 3.1.3 and the interface
    RStudio.

! [image] (C: /Users/thiago/OneDrive/UNESP/Pos_graduacao/Eco/2015/Estatistica_2015/Aulas/Aula_1_Intro_2015/figs/crybaby.jpg) {width = "1.5in"}

http://www.jillgreenberg.com/
Send feedback
History
Saved
Community
